<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "wp_falcleaner"
 *
 * Auto generated by Extension Builder 2020-11-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'FAL cleaner',
    'description' => 'Find duplicate files and clean up database and filesystem.',
    'category' => 'module',
    'author' => 'Gernot Ploiner',
    'author_email' => 'gp@webprofil.at',
    'state' => 'stable',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '2.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
